# Use a lightweight Node.js image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application's code
COPY . .

# Install dependencies
RUN npm install

# Build the NestJS application
RUN npm run build

# Expose the port your application runs on (default for NestJS is 3000)
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "run", "start:prod"]
